defaults:
  - model: fenet
  - datamodule: mvsa

gpus: 1
# number of cpu threads for data loading
num_workers: 14
random_seed: 1590258941
wandb_log: True

training:
  epochs: 100
  batch_size: 8
  # accumulate gradients for this many batches
  acc_batches: 1
  # checkpointing
  save_ckpts: 3
  monitor: val_loss
  mode: min
  patience: 5

testing:
  log_dir: 'outputs/model.mlp.MLP/2020-11-19/18-17-17'
  test_best_k: 5
  batch_size: 8

metrics:
  - _target_: pytorch_lightning.metrics.classification.Accuracy
  - _target_: pytorch_lightning.metrics.classification.F1
    num_classes: 3
    average: 'macro'

hydra:
  run:
    dir: ./outputs/${model._target_}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./outputs/${model._target_}/${now:%Y-%m-%d}/${now:%H-%M-%S}
