# @package _global_
model:
  _target_: model.dummymodel.DummyModel

loss:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-3

loop:
  _target_: loop.DefaultClassificationLoop